"""
mcp-reasoning — Reverse-Proxy + WAF Intelligence (a+b+c) offline testleri:
fingerprint_waf, classify_response, discover_origin, adaptive_evasion_step +
WAF-aware evolve_payload. Deterministik, canlı istek/network YOK.
"""
import json
from conftest import load_server


def _r():
    return load_server("reasoning")


# ───────────────────── (a) fingerprint_waf ─────────────────────
def test_fingerprint_cloudflare_cdn():
    mod = _r()
    out = json.loads(mod.fingerprint_waf(
        headers="Server: cloudflare\nCF-RAY: 7a2b\ncf-cache-status: DYNAMIC",
        body="Attention Required! | Cloudflare", status_code=403))
    assert out["vendor"] == "cloudflare"
    assert out["is_cdn_reverse_proxy"] is True
    assert out["advise_origin_discovery"] is True
    assert "case_swap" in out["recommended_operators"]


def test_fingerprint_modsecurity_not_cdn():
    mod = _r()
    out = json.loads(mod.fingerprint_waf(
        body="This error was generated by Mod_Security", status_code=406))
    assert out["vendor"] == "modsecurity"
    assert out["is_cdn_reverse_proxy"] is False
    assert out["advise_origin_discovery"] is False


def test_fingerprint_unknown():
    mod = _r()
    out = json.loads(mod.fingerprint_waf(headers="Server: nginx", body="hello", status_code=200))
    assert out["waf_detected"] is False
    assert out["vendor"] == "unknown"


# ───────────────────── (c) classify_response ─────────────────────
def test_classify_waf_block():
    mod = _r()
    out = json.loads(mod.classify_response(403, "Server: cloudflare\ncf-ray: 1", "Attention Required"))
    assert out["classification"] == "waf_block"


def test_classify_rate_limit():
    mod = _r()
    out = json.loads(mod.classify_response(429, "Retry-After: 30", "too many requests"))
    assert out["classification"] == "rate_limit"


def test_classify_app_error_means_passed_waf():
    mod = _r()
    out = json.loads(mod.classify_response(500, "", "You have an error in your SQL syntax near"))
    assert out["classification"] == "app_error"


def test_classify_origin_reached():
    mod = _r()
    out = json.loads(mod.classify_response(200, "Server: nginx", "welcome home"))
    assert out["classification"] == "origin_reached"


# ───────────────────── (b) discover_origin ─────────────────────
def test_discover_origin_ranks_and_filters_cdn():
    mod = _r()
    out = json.loads(mod.discover_origin(
        "example.com",
        historical_ips="104.18.5.5 1.2.3.4",          # 104.18.* = Cloudflare CDN → elenmeli
        leaked_headers="X-Real-IP: 5.6.7.8",          # en güçlü sinyal
        candidate_ips="172.67.1.1"))                  # 172.67.* = Cloudflare → elenmeli
    assert out["best_candidate"]["ip"] == "5.6.7.8"
    ips = {r["ip"] for r in out["origin_candidates"]}
    assert "5.6.7.8" in ips and "1.2.3.4" in ips
    assert "104.18.5.5" not in ips and "172.67.1.1" not in ips   # CDN elendi
    assert all(not r["is_cdn"] for r in out["origin_candidates"])
    assert any("Host: example.com" in t for t in out["direct_to_origin_tests"])


def test_discover_origin_emits_recon_when_empty():
    mod = _r()
    out = json.loads(mod.discover_origin("example.com"))
    assert out["best_candidate"] is None
    assert any("crt.sh" in c for c in out["live_recon_commands"])


# ───────────────────── WAF-aware evolve_payload ─────────────────────
def test_evolve_payload_waf_prioritizes_operators():
    mod = _r()
    out = json.loads(mod.evolve_payload(
        payload="1 UNION SELECT user,pass FROM users", technique="sql_injection",
        waf="cloudflare", generations=1, population=10))
    assert out["waf"] == "cloudflare"
    # cloudflare-tercihli & sql-ailesinde olan operatörler ÖNE alınmış olmalı
    assert out["operators_available"][:3] == ["case_swap", "url_encode", "keyword_split"]


def test_normalize_waf_aliases():
    mod = _r()
    assert mod._normalize_waf("Incapsula") == "imperva_incapsula"
    assert mod._normalize_waf("F5") == "f5_big_ip_asm"
    assert mod._normalize_waf("mod_security") == "modsecurity"
    assert mod._normalize_waf("CloudFront") == "aws_waf"


# ───────────────────── (c) adaptive_evasion_step (kapalı döngü) ─────────────────────
def test_adaptive_evasion_waf_block_loops():
    mod = _r()
    out = json.loads(mod.adaptive_evasion_step(
        payload="1 UNION SELECT 1", technique="sql_injection", status_code=403,
        resp_headers="Server: cloudflare\ncf-ray: zz", resp_body="Attention Required! | Cloudflare",
        domain="example.com"))
    assert out["classification"] == "waf_block"
    assert out["waf"]["vendor"] == "cloudflare"
    assert out["next_variants"]                       # WAF-aware varyantlar üretildi
    assert "origin_bypass" in out                     # CDN → origin keşfi önerildi


def test_adaptive_evasion_rate_limit_throttles():
    mod = _r()
    out = json.loads(mod.adaptive_evasion_step(
        payload="x", technique="sql_injection", status_code=429,
        resp_headers="Retry-After: 10", resp_body="too many requests, slow down"))
    assert out["classification"] == "rate_limit"
    assert "throttle" in out
    assert out["next_variants"] == []                 # rate-limit'te payload yakma
